#!/usr/bin/env node
/**
 * Bundles the "three" package into ONE self-contained, import-free ESM file
 * so it can be embedded as a data: URI import-map entry inside a generated
 * game's HTML (see src/lib/three-vendor.ts) — the game stays a single,
 * fully-offline file even when it uses 3D, on the platform's preview,
 * download, AND once published as a standalone static file.
 *
 * Why bundle instead of copying three's own build output: three's own
 * "three.module.min.js" imports from a sibling "./three.core.min.js" file,
 * which breaks once loaded from a data: URI (relative imports can't resolve
 * against an opaque data: base). esbuild inlines everything into one flat
 * file with zero import statements, side-stepping that entirely.
 */

import { build } from 'esbuild';
import { writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = dirname(dirname(fileURLToPath(import.meta.url)));
const outDir = join(repo, 'src/lib/vendor');

// Named exports only (not `export *`) — lets esbuild tree-shake to just what
// the system prompt actually teaches Gemini to use (primitives + basic
// lighting/materials, see CHILD_SYSTEM_PROMPT in src/lib/gemini.ts). Add a
// name here AND to the prompt together if the 3D vocabulary grows.
const THREE_EXPORTS = [
  'Scene', 'PerspectiveCamera', 'WebGLRenderer', 'Clock', 'Color', 'Fog',
  'Group', 'Vector3',
  'BoxGeometry', 'SphereGeometry', 'ConeGeometry', 'CylinderGeometry',
  'PlaneGeometry', 'TorusGeometry', 'CapsuleGeometry', 'RingGeometry',
  'MeshStandardMaterial', 'MeshBasicMaterial', 'Mesh',
  'AmbientLight', 'DirectionalLight', 'PointLight', 'HemisphereLight',
];

const result = await build({
  stdin: {
    contents: `export { ${THREE_EXPORTS.join(', ')} } from 'three';`,
    resolveDir: repo,
    loader: 'js',
    sourcefile: 'three-entry.js',
  },
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2019',
  minify: true,
  write: false,
});

await mkdir(outDir, { recursive: true });
const out = join(outDir, 'three-bundle.generated.js');
await writeFile(
  out,
  `// GENERATED by scripts/vendor-three.mjs from the "three" npm package — do not edit by hand.\n` +
    result.outputFiles[0].text,
);
console.log(`✓ three.js vendored → src/lib/vendor/three-bundle.generated.js (${(result.outputFiles[0].text.length / 1024).toFixed(0)} KB)`);
