#!/usr/bin/env node
/**
 * Bundles the "cannon-es" npm package into ONE self-contained, import-free ES
 * module and publishes it to the shared immutable asset host
 * (assets.ariantra.com) — the SECOND engine, beside three.
 * See docs/2026-07-29_PRD_Physics.md Phase 2.
 *
 * Direct sibling of vendor-three.mjs: same four stages, same immutability
 * contract, same upload-then-verify rule. Read that file first — everything
 * structural is explained there and deliberately not repeated here.
 *
 * Why cannon-es and not rapier/ammo (measured 2026-07-29, don't re-litigate
 * without re-measuring): rapier3d ships a 1.53 MB WASM payload, which breaches
 * the §8 2 MB first-load cap on its own, and is Apache-2.0 — the manifest
 * validator allows only CC0/MIT for `engine`. cannon-es is MIT and bundles to
 * ~92 KB for the curated export list below.
 *
 * The export list is CURATED (named exports only, so esbuild tree-shakes):
 * every name here must ALSO be taught in physics-playbook.ts's engine clause
 * and allowed by cannon-import-lint.ts — a game importing an untaught name
 * dies on its import line, and no self-healing pass can patch that away. The
 * lint test pins the three lists together.
 *
 *   node --env-file=../Ariantra-Platform/.env scripts/vendor-cannon.mjs --upload
 */

import { build } from 'esbuild';
import { S3Client, PutObjectCommand, HeadObjectCommand } from '@aws-sdk/client-s3';
import { createHash } from 'node:crypto';
import { writeFile, mkdir } from 'node:fs/promises';
import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = dirname(dirname(fileURLToPath(import.meta.url)));
const outDir = join(repo, '.assets-out');
const manifestPath = join(repo, 'src/lib/assets/manifest.json');

const ASSET_HOST_ORIGIN = 'https://assets.ariantra.com';
const ENGINE_BUDGET_BYTES = 650_000; // shared with three (BUDGET_BYTES.engine, manifest.ts)
const CACHE_CONTROL = 'public, max-age=31536000, immutable';

// Keep in lockstep with CANNON_IMPORT_NAMES in src/lib/assets/cannon-import-lint.ts
// (pinned by test) and with what the physics prompt clause teaches.
export const CANNON_EXPORTS = [
  'World', 'Body', 'Vec3', 'Quaternion',
  'Box', 'Sphere', 'Plane', 'Cylinder',
  'Material', 'ContactMaterial',
];

// ── stage 1: build ───────────────────────────────────────────────────────────
const entry = `export { ${CANNON_EXPORTS.join(', ')} } from 'cannon-es';`;

const result = await build({
  stdin: { contents: entry, resolveDir: repo, loader: 'js', sourcefile: 'cannon-entry.js' },
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2019',
  minify: true,
  legalComments: 'inline', // cannon-es is MIT — its notice rides inside the served bundle
  write: false,
});

const source =
  `// GENERATED by scripts/vendor-cannon.mjs from the "cannon-es" npm package (MIT — notice preserved below). Do not edit.\n` +
  result.outputFiles[0].text;
const bytes = Buffer.from(source, 'utf8');
const sha256 = createHash('sha256').update(bytes).digest('hex');
const fileName = `physics.${sha256.slice(0, 6)}.js`;
const url = `${ASSET_HOST_ORIGIN}/${fileName}`;

for (const mustContain of CANNON_EXPORTS) {
  if (!source.includes(mustContain)) {
    console.error(`✗ bundle is missing ${mustContain} — refusing`);
    process.exit(1);
  }
}
if (bytes.length > ENGINE_BUDGET_BYTES) {
  console.error(`✗ bundle is ${bytes.length} bytes > engine budget ${ENGINE_BUDGET_BYTES} — refusing (PRD §8)`);
  process.exit(1);
}

await mkdir(outDir, { recursive: true });
await writeFile(join(outDir, fileName), bytes);
console.log(`✓ built ${fileName} (${(bytes.length / 1024).toFixed(0)} KB, sha256 ${sha256.slice(0, 12)}…) → .assets-out/`);

if (!process.argv.includes('--upload')) {
  console.log(`\nDry run (no --upload). Next stages would:`);
  console.log(`  2. PutObject → {S3_PREFIX}sites/assets/${fileName}  Cache-Control: ${CACHE_CONTROL}`);
  console.log(`  3. GET ${url} and verify sha256`);
  console.log(`  4. write manifest entry + run manifest contract tests`);
  process.exit(0);
}

// ── stage 2: upload (append-only) ───────────────────────────────────────────
const { AWS_REGION, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, S3_BUCKET } = process.env;
const S3_PREFIX = process.env.S3_PREFIX || 'ariantra/';
if (!AWS_REGION || !AWS_ACCESS_KEY_ID || !AWS_SECRET_ACCESS_KEY || !S3_BUCKET) {
  console.error('✗ --upload needs AWS env (run with: node --env-file=../Ariantra-Platform/.env scripts/vendor-cannon.mjs --upload)');
  process.exit(1);
}
const client = new S3Client({ region: AWS_REGION, credentials: { accessKeyId: AWS_ACCESS_KEY_ID, secretAccessKey: AWS_SECRET_ACCESS_KEY } });
const key = `${S3_PREFIX}sites/assets/${fileName}`;

let alreadyThere = false;
try {
  await client.send(new HeadObjectCommand({ Bucket: S3_BUCKET, Key: key }));
  alreadyThere = true;
  console.log(`• ${key} already exists — append-only host, leaving it untouched`);
} catch { /* 404 = new object */ }

if (!alreadyThere) {
  await client.send(new PutObjectCommand({
    Bucket: S3_BUCKET, Key: key, Body: bytes,
    ContentType: 'text/javascript', CacheControl: CACHE_CONTROL,
  }));
  console.log(`✓ uploaded s3://${S3_BUCKET}/${key}`);
}

// ── stage 3: verify through the public path ─────────────────────────────────
const res = await fetch(url);
if (!res.ok) {
  console.error(`✗ ${url} → HTTP ${res.status} — NOT adding a manifest entry (upload-then-verify).`);
  process.exit(1);
}
const served = Buffer.from(await res.arrayBuffer());
const servedSha = createHash('sha256').update(served).digest('hex');
if (servedSha !== sha256) {
  console.error(`✗ served hash ≠ built hash — refusing the manifest entry`);
  process.exit(1);
}
if (!(res.headers.get('cache-control') || '').includes('immutable')) {
  console.error(`✗ served Cache-Control lacks immutable — fix headers first`);
  process.exit(1);
}
console.log(`✓ verified ${url} (200, sha256 match, immutable)`);

// ── stage 4: manifest entry, gated by the contract tests ────────────────────
const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
const entryJson = {
  // NOT 'cannon': the military asset batch ships a MODEL called `cannon` (the
  // wheeled artillery piece). Keying this entry as 'cannon' made the findIndex
  // below match that model and REPLACE it — caught 2026-07-29 by the taxonomy
  // tests, which is exactly why stage 4 runs them. The lookup is name+type
  // qualified now too, but the distinct name is the real fix.
  name: 'physics',
  type: 'engine',
  url,
  bytes: bytes.length,
  license: 'MIT', // engine-only exception; library assets stay CC0-only (manifest.ts)
  sourceUrl: 'https://github.com/pmndrs/cannon-es',
  sha256,
};
const existing = manifest.assets.findIndex((a) => a.name === 'physics' && a.type === 'engine');
if (existing >= 0) manifest.assets[existing] = entryJson;
else manifest.assets.push(entryJson);
writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');

execFileSync('npx', ['vitest', 'run', 'src/lib/assets/'], { cwd: repo, stdio: 'inherit' });
console.log(`✓ manifest entry written and contract tests green — commit src/lib/assets/manifest.json`);
