// The curation layer for the asset library (2026-07-24). Kept OUT of
// manifest.json deliberately: that file is generated by scripts/vendor-*.mjs and
// describes only mechanical facts about published bytes (hash, size, licence,
// URL). Which category a model belongs to and what a kid might call it are
// editorial judgements — they belong in a reviewed, typed, hand-maintained file
// that a pipeline re-run can never silently overwrite.
//
// This replaces the hand-maintained GENRES[].models arrays that used to live in
// model-select.ts. Membership now travels with the asset, so adding a model can
// no longer desync from the selection layer (CLAUDE.md §4 — Open/Closed: extend
// config, don't edit call sites). asset-taxonomy.test.ts pins the migration.
//
// `tags` are synonyms the NAME does not already cover — matching always checks
// the name too, so self-evident models (apple, banana) legitimately carry few.
// Tags are selection/search metadata ONLY and are never rendered into the
// prompt, which keeps catalog tokens independent of how richly we tag.

/** Genre buckets. Each renders as one category heading in the prompt catalog
 *  (prompt-catalog.ts) and pairs with a trigger regex in model-select.ts. */
export const GENRE_IDS = [
  "people", "racing", "platformer", "space", "animals",
  "castle", "city", "nature", "water", "food",
] as const;
export type GenreId = (typeof GENRE_IDS)[number];

/** Models built on a shared skeleton, so they carry an identical set of named
 *  animation clips. This is a TECHNICAL fact, deliberately not a genre: the
 *  `people` genre also contains `grandstand`, and telling the model a stadium
 *  has a "walk" clip is exactly the kind of confident-but-wrong instruction
 *  that produces a broken game. Only a rig may drive the shared-clips prompt
 *  line. */
export const RIG_IDS = ["kenney_blocky"] as const;
export type RigId = (typeof RIG_IDS)[number];

export interface TaxonomyEntry {
  /** At least one — an ungrouped model is unreachable in the catalog. */
  genres: GenreId[];
  /** Extra words a kid might say. May be empty when the name says it all. */
  tags: string[];
  /** Set only when the model shares a skeleton (and therefore a clip list)
   *  with others. Absent for one-off meshes. */
  rig?: RigId;
}

const TAG_RE = /^[a-z0-9_]{1,32}$/;

export const TAXONOMY: Record<string, TaxonomyEntry> = {
  car: { genres: ["racing", "city"], tags: ["auto", "automobile", "vehicle", "racer"] },
  dino: { genres: ["animals", "castle"], tags: ["dinosaur", "trex", "rex", "prehistoric"] },
  tree: { genres: ["platformer", "nature"], tags: ["forest", "wood", "leaves"] },
  coin: { genres: ["racing", "platformer"], tags: ["money", "gold", "pickup", "collect", "treasure"] },
  rocket: { genres: ["space"], tags: ["launch", "blastoff", "missile"] },
  dog: { genres: ["animals", "nature"], tags: ["puppy", "pup", "doggy", "pet", "hound"] },
  cat: { genres: ["animals"], tags: ["kitten", "kitty", "pet", "feline"] },
  fish: { genres: ["animals", "water"], tags: ["swim", "goldfish", "sea"] },
  boat: { genres: ["water"], tags: ["ship", "sail", "yacht", "ferry"] },
  robot: { genres: ["castle"], tags: ["android", "bot", "mech", "droid"] },
  tower: { genres: ["castle"], tags: ["castle", "fortress", "turret"] },
  spaceship: { genres: ["space"], tags: ["starship", "shuttle", "ufo"] },
  ufo: { genres: ["space"], tags: ["flyingsaucer", "alien", "saucer"] },
  helicopter: { genres: ["space", "city"], tags: ["chopper", "heli", "fly"] },
  ghost: { genres: ["castle"], tags: ["spooky", "spirit", "haunted", "phantom"] },
  police: { genres: ["racing", "city"], tags: ["cop", "patrol", "siren", "emergency"] },
  firetruck: { genres: ["racing", "city"], tags: ["fire", "engine", "emergency", "siren", "rescue"] },
  star: { genres: ["platformer", "space"], tags: ["pickup", "collect", "sparkle"] },
  key: { genres: ["platformer", "castle"], tags: ["unlock", "pickup"] },
  chest: { genres: ["platformer", "castle", "water"], tags: ["treasure", "loot", "box"] },
  skyscraper: { genres: ["city"], tags: ["tower", "building", "tall"] },
  house: { genres: ["city"], tags: ["home", "building", "cottage"] },
  pine: { genres: ["nature"], tags: ["tree", "conifer", "fir", "forest"] },
  rock: { genres: ["nature"], tags: ["stone", "boulder"] },
  alien: { genres: ["space"], tags: ["martian", "extraterrestrial", "monster"] },
  bird: { genres: ["animals", "nature"], tags: ["fly", "sparrow", "wings"] },
  shark: { genres: ["water"], tags: ["jaws", "predator", "sea"] },
  hero: { genres: ["platformer", "castle"], tags: ["player", "character", "adventurer", "knight"] },
  heart: { genres: ["platformer"], tags: ["life", "health", "love", "pickup"] },
  gem: { genres: ["platformer", "castle"], tags: ["jewel", "diamond", "crystal", "treasure", "pickup"] },
  bomb: { genres: ["platformer"], tags: ["explosive", "tnt", "dynamite"] },
  spring: { genres: ["platformer"], tags: ["bounce", "jump", "trampoline"] },
  flag: { genres: ["platformer"], tags: ["banner", "goal", "checkpoint"] },
  mushroom: { genres: ["platformer", "nature"], tags: ["toadstool", "fungus"] },
  barrel: { genres: ["platformer"], tags: ["keg", "drum"] },
  crate: { genres: ["platformer"], tags: ["box", "wooden"] },
  taxi: { genres: ["racing"], tags: ["cab", "yellow"] },
  ambulance: { genres: ["racing"], tags: ["emergency", "siren", "hospital", "rescue", "medic"] },
  tractor: { genres: ["racing"], tags: ["farm", "plough", "farmer"] },
  catapult: { genres: ["castle"], tags: ["siege", "launcher"] },
  bridge: { genres: ["castle"], tags: ["crossing", "span"] },
  burger: { genres: ["food"], tags: ["hamburger", "cheeseburger", "fastfood"] },
  ice_cream: { genres: ["food"], tags: ["icecream", "cone", "dessert", "sundae"] },
  donut: { genres: ["food"], tags: ["doughnut", "dessert", "sweet"] },
  apple: { genres: ["food"], tags: ["fruit"] },
  chicken: { genres: ["animals", "food"], tags: ["hen", "chick", "farm", "rooster"] },
  bat: { genres: ["castle"], tags: ["spooky", "cave", "wings", "vampire"] },
  dolphin: { genres: ["water"], tags: ["sea", "swim", "porpoise"] },
  bee: { genres: ["animals"], tags: ["bumblebee", "honey", "buzz", "insect"] },
  sword: { genres: ["castle"], tags: ["blade", "weapon", "knight"] },
  garbage_truck: { genres: ["racing", "city"], tags: ["bin", "trash", "rubbish", "recycling"] },
  pickup_truck: { genres: ["racing"], tags: ["ute", "lorry", "van"] },
  gokart: { genres: ["racing"], tags: ["kart", "buggy", "racer"] },
  ballista: { genres: ["castle"], tags: ["siege", "crossbow"] },
  trebuchet: { genres: ["castle"], tags: ["siege", "launcher"] },
  battering_ram: { genres: ["castle"], tags: ["siege", "ram"] },
  castle_gate: { genres: ["castle"], tags: ["castle", "entrance", "portcullis"] },
  drawbridge: { genres: ["castle"], tags: ["castle", "bridge"] },
  siege_tower: { genres: ["castle"], tags: ["siege"] },
  castle_door: { genres: ["castle"], tags: ["castle", "entrance"] },
  lock: { genres: ["platformer"], tags: ["locked", "padlock"] },
  lever: { genres: ["platformer"], tags: ["switch", "handle"] },
  saw: { genres: ["platformer"], tags: ["blade", "hazard", "spike", "danger"] },
  signpost: { genres: ["platformer"], tags: ["sign", "arrow", "direction"] },
  ladder: { genres: ["platformer"], tags: ["climb", "steps"] },
  pizza: { genres: ["food"], tags: ["slice", "italian", "fastfood"] },
  hotdog: { genres: ["food"], tags: ["sausage", "fastfood"] },
  banana: { genres: ["food"], tags: ["fruit"] },
  watermelon: { genres: ["food"], tags: ["fruit", "melon"] },
  cake: { genres: ["food"], tags: ["dessert", "birthday", "sweet"] },
  cupcake: { genres: ["food"], tags: ["dessert", "muffin", "sweet"] },
  taco: { genres: ["food"], tags: ["mexican", "fastfood"] },
  carrot: { genres: ["food"], tags: ["vegetable", "veggie"] },
  strawberry: { genres: ["food"], tags: ["fruit", "berry"] },
  sandwich: { genres: ["food"], tags: ["sub", "lunch", "bread"] },
  corn: { genres: ["food"], tags: ["maize", "vegetable", "cob"] },
  sushi: { genres: ["food"], tags: ["japanese", "fish", "rice"] },
  egg: { genres: ["food"], tags: ["breakfast"] },
  muffin: { genres: ["food"], tags: ["dessert", "cupcake", "sweet"] },
  cherries: { genres: ["food"], tags: ["cherry", "fruit"] },
  cactus: { genres: ["nature"], tags: ["desert", "prickly", "spiky"] },
  campfire: { genres: ["nature"], tags: ["fire", "camp", "flames"] },
  canoe: { genres: ["nature", "water"], tags: ["kayak", "paddle", "row"] },
  tent: { genres: ["nature"], tags: ["camp", "camping", "shelter"] },
  palm_tree: { genres: ["nature"], tags: ["tree", "beach", "tropical", "island"] },
  statue: { genres: ["nature"], tags: ["monument", "sculpture"] },
  toadstool: { genres: ["nature"], tags: ["mushroom", "fungus"] },
  office_building: { genres: ["city"], tags: ["office", "building", "work"] },
  shop: { genres: ["city"], tags: ["store", "market", "shopping"] },
  apartment: { genres: ["city"], tags: ["flat", "building", "block"] },
  driveway: { genres: ["city"], tags: ["road", "path", "drive"] },
  planter: { genres: ["city"], tags: ["plant", "pot", "flowerbed"] },
  race_track_straight: { genres: ["racing"], tags: ["road", "track", "tarmac"] },
  race_track_curve: { genres: ["racing"], tags: ["road", "track", "bend", "corner"] },
  finish_line: { genres: ["racing"], tags: ["finish", "start", "goal"] },
  checkered_flag: { genres: ["racing"], tags: ["finish", "win", "race"] },
  grandstand: { genres: ["people", "racing"], tags: ["stadium", "seats", "crowd", "audience", "bleachers"] },
  pit_garage: { genres: ["racing"], tags: ["pitstop", "garage", "pit"] },
  dragon: { genres: ["castle"], tags: ["fire", "wings", "beast", "monster"] },
  dragon_evolved: { genres: ["castle"], tags: ["fire", "wings", "beast", "monster", "boss"] },
  // ── City batch 2 (2026-07-24). Buildings named from renders of the GLBs;
  // the kits ship letter names only. Every one is `city`; the houses also
  // carry `people` words in tags because kids say "a street where people live".
  office_small: { genres: ["city"], tags: ["office", "building", "shop", "block"] },
  office_wide: { genres: ["city"], tags: ["office", "building", "wide", "block"] },
  office_block: { genres: ["city"], tags: ["office", "building", "block", "storeys"] },
  flats: { genres: ["city"], tags: ["apartments", "building", "balcony", "block", "housing"] },
  garden_apartment: { genres: ["city", "nature"], tags: ["apartments", "building", "plants", "green", "balcony"] },
  long_office: { genres: ["city"], tags: ["office", "building", "long", "wide"] },
  narrow_tower: { genres: ["city"], tags: ["tower", "tall", "thin", "building", "antenna"] },
  mall: { genres: ["city"], tags: ["shopping", "shops", "store", "centre", "market"] },
  glass_tower: { genres: ["city"], tags: ["skyscraper", "tall", "glass", "office", "tower"] },
  antenna_tower: { genres: ["city"], tags: ["skyscraper", "tall", "aerial", "mast", "tower"] },
  white_tower: { genres: ["city"], tags: ["skyscraper", "tall", "white", "office", "tower"] },
  awning: { genres: ["city"], tags: ["canopy", "shade", "shopfront", "shelter"] },
  parasol: { genres: ["city"], tags: ["umbrella", "shade", "cafe", "sunshade"] },
  family_house: { genres: ["city"], tags: ["home", "house", "family", "roof", "suburb"] },
  bungalow: { genres: ["city"], tags: ["home", "house", "single", "storey", "cottage"] },
  cottage: { genres: ["city", "nature"], tags: ["home", "house", "chimney", "cosy", "country"] },
  town_house: { genres: ["city"], tags: ["home", "house", "two", "storey", "terrace"] },
  dark_house: { genres: ["city"], tags: ["home", "house", "black", "modern", "garden"] },
  porch_house: { genres: ["city"], tags: ["home", "house", "porch", "carport", "veranda"] },
  modern_house: { genres: ["city"], tags: ["home", "house", "modern", "flat", "roof", "boxy"] },
  modern_villa: { genres: ["city"], tags: ["home", "house", "villa", "modern", "luxury"] },
  stilt_house: { genres: ["city"], tags: ["home", "house", "stilts", "raised", "balcony"] },
  garage_house: { genres: ["city"], tags: ["home", "house", "garage", "driveway", "suburb"] },
  fence: { genres: ["city", "nature"], tags: ["railing", "garden", "boundary", "wall", "picket"] },
  low_fence: { genres: ["city", "nature"], tags: ["railing", "garden", "boundary", "short", "picket"] },
  garden_path: { genres: ["city", "nature"], tags: ["path", "walkway", "pavement", "trail"] },
  stone_path: { genres: ["city", "nature"], tags: ["path", "stones", "stepping", "walkway", "trail"] },
  short_driveway: { genres: ["city"], tags: ["drive", "parking", "road", "tarmac"] },
  small_tree: { genres: ["nature", "city"], tags: ["tree", "bush", "shrub", "sapling", "garden"] },

  // ── Vehicles batch 2 (2026-07-24). Mostly racing + city; `digger` is a work
  // machine so it leans city/nature rather than racing.
  sedan: { genres: ["racing", "city"], tags: ["car", "saloon", "auto", "family"] },
  sports_car: { genres: ["racing", "city"], tags: ["car", "fast", "racer", "speed", "sport"] },
  hatchback: { genres: ["racing", "city"], tags: ["car", "small", "auto", "compact"] },
  suv: { genres: ["racing", "city"], tags: ["car", "jeep", "offroad", "4x4", "big"] },
  luxury_suv: { genres: ["racing", "city"], tags: ["car", "jeep", "posh", "4x4", "luxury"] },
  van: { genres: ["racing", "city"], tags: ["minivan", "camper", "auto", "people", "carrier"] },
  delivery_van: { genres: ["racing", "city"], tags: ["delivery", "parcel", "post", "courier", "van"] },
  truck: { genres: ["racing", "city"], tags: ["lorry", "flatbed", "haul", "cargo", "big"] },
  digger: { genres: ["city", "nature"], tags: ["excavator", "shovel", "bulldozer", "build", "construction", "jcb"] },
  future_car: { genres: ["racing", "space"], tags: ["futuristic", "concept", "hover", "fast", "sci_fi"] },
  race_kart: { genres: ["racing"], tags: ["kart", "gokart", "buggy", "racer", "second"] },
  traffic_cone: { genres: ["racing", "city"], tags: ["cone", "obstacle", "roadworks", "marker", "hazard"] },

  // Batch 2 (2026-07-24) — the other 12 of the kit's 18. Same rig, so the same
  // clip set; named from renders of the actual GLBs, not the 64px thumbnails
  // (which had me calling the two mechs "knights" and the orc a "goblin").
  grandpa: { genres: ["people", "city"], tags: ["grandad", "grandfather", "old", "man", "beard", "apron", "elder"], rig: "kenney_blocky" },
  gamer: { genres: ["people", "city"], tags: ["player", "boy", "teen", "controller", "man", "casual"], rig: "kenney_blocky" },
  mascot: { genres: ["people", "platformer"], tags: ["costume", "suit", "hero", "yellow", "character"], rig: "kenney_blocky" },
  mech: { genres: ["castle", "space"], tags: ["robot", "android", "armour", "battle", "droid"], rig: "kenney_blocky" },
  purple_mech: { genres: ["castle", "space"], tags: ["robot", "android", "armour", "battle", "droid"], rig: "kenney_blocky" },
  plumber: { genres: ["people", "city"], tags: ["worker", "moustache", "handyman", "man", "builder"], rig: "kenney_blocky" },
  zombie: { genres: ["castle", "people"], tags: ["undead", "monster", "spooky", "hallowe_en", "green"], rig: "kenney_blocky" },
  explorer: { genres: ["people", "nature"], tags: ["adventurer", "scout", "ranger", "safari", "man", "satchel"], rig: "kenney_blocky" },
  kimono_woman: { genres: ["people", "city"], tags: ["kimono", "japanese", "lady", "woman", "geisha", "traditional"], rig: "kenney_blocky" },
  orc: { genres: ["castle"], tags: ["monster", "tusks", "green", "troll", "brute", "goblin"], rig: "kenney_blocky" },
  businessman: { genres: ["people", "city"], tags: ["suit", "office", "worker", "boss", "man", "tie"], rig: "kenney_blocky" },
  ninja: { genres: ["castle", "people"], tags: ["assassin", "warrior", "stealth", "shinobi", "masked"], rig: "kenney_blocky" },

  man: { genres: ["people", "city"], tags: ["guy", "dad", "father", "person", "human", "adult"], rig: "kenney_blocky" },
  woman: { genres: ["people", "city"], tags: ["lady", "mum", "mom", "mother", "person", "human", "adult"], rig: "kenney_blocky" },
  girl: { genres: ["people", "city"], tags: ["kid", "child", "daughter", "sister"], rig: "kenney_blocky" },
  scientist: { genres: ["people"], tags: ["doctor", "professor", "lab", "inventor"], rig: "kenney_blocky" },
  police_officer: { genres: ["people", "city"], tags: ["cop", "policeman", "policewoman", "sheriff"], rig: "kenney_blocky" },
  pirate: { genres: ["people", "castle", "water"], tags: ["captain", "buccaneer", "sailor"], rig: "kenney_blocky" },
};

export function genresOf(name: string): readonly GenreId[] {
  return TAXONOMY[name]?.genres ?? [];
}

export function tagsOf(name: string): readonly string[] {
  return TAXONOMY[name]?.tags ?? [];
}

/** Members of a genre, filtered to what the manifest actually carries — so a
 *  curation entry for an asset we later drop can never name a dead model. */
export function modelsInGenre(genre: GenreId, available: ReadonlySet<string>): string[] {
  return Object.keys(TAXONOMY).filter((n) => available.has(n) && TAXONOMY[n]!.genres.includes(genre));
}

/** Models sharing a skeleton, filtered to what the manifest carries. This — not
 *  the `people` genre — is what may drive the shared-animation-clips prompt
 *  line, so scenery that merely sits in a people-ish genre (grandstand) can
 *  never be described to the model as having a walk cycle. */
export function modelsWithRig(rig: RigId, available: ReadonlySet<string>): string[] {
  return Object.keys(TAXONOMY).filter((n) => available.has(n) && TAXONOMY[n]!.rig === rig);
}

/**
 * Fails closed on malformed or incomplete curation. Called by the test suite
 * against the real manifest, so a model added without a taxonomy entry breaks
 * the build rather than quietly disappearing from every category heading.
 */
export function validateTaxonomy(
  modelNames: readonly string[],
  taxonomy: Record<string, TaxonomyEntry> = TAXONOMY,
): void {
  for (const name of modelNames) {
    const entry = taxonomy[name];
    if (!entry) throw new Error(`no taxonomy entry for model "${name}" — every model needs a genre and tags`);
    if (entry.genres.length === 0) throw new Error(`"${name}" has no genre — it would be unreachable in the catalog`);
    for (const genre of entry.genres) {
      if (!(GENRE_IDS as readonly string[]).includes(genre)) {
        throw new Error(`unknown genre "${genre}" on "${name}" — must be one of ${GENRE_IDS.join(", ")}`);
      }
    }
    const seen = new Set<string>();
    for (const tag of entry.tags) {
      if (!TAG_RE.test(tag)) throw new Error(`tag must match ${TAG_RE} on "${name}": "${tag}"`);
      if (seen.has(tag)) throw new Error(`duplicate tag "${tag}" on "${name}"`);
      seen.add(tag);
    }
  }
}
