/**
 * The admin Models tab's data. Two things are worth testing here and both are
 * about being WRONG rather than being missing:
 *
 *   1. a model reported as able to walk when it cannot — the tab exists to
 *      answer "what can this do", and a confident wrong answer is worse than
 *      no tab at all (this is the "make the elephant walk" bug in report form);
 *   2. the abilities file drifting from the manifest — it is committed, not
 *      computed at runtime, so nothing else would notice.
 */
import { describe, it, expect } from "vitest";
import { modelCatalogue, deriveAbilities, shortClip } from "./model-catalogue";
import { RETIRED } from "./retired";
import manifest from "./manifest.json";
import type { AssetManifest } from "./manifest";

const modelNames = (manifest as AssetManifest).assets.filter((a) => a.type === "model").map((a) => a.name);

describe("deriveAbilities — reading clip names honestly", () => {
  it("C.1 recognises locomotion under the Quaternius armature prefixes", () => {
    const a = deriveAbilities(["AnimalArmature|AnimalArmature|AnimalArmature|Walk", "AnimalArmature|Run", "CharacterArmature|Idle"]);
    expect(a).toEqual(expect.arrayContaining(["walk", "run", "idle"]));
  });

  it("C.2 recognises flying and swimming, which are NOT walking", () => {
    expect(deriveAbilities(["CharacterArmature|Fast_Flying", "CharacterArmature|Flying_Idle"])).toContain("fly");
    expect(deriveAbilities(["Armature|Swim"])).toContain("swim");
    expect(deriveAbilities(["Armature|Swim"])).not.toContain("walk");
  });

  it("C.3 a model with NO clips has NO abilities — never infers from the name", () => {
    // The whole 2026-08-20 safari cull came from assuming an animal animates.
    expect(deriveAbilities([])).toEqual([]);
  });

  it("C.4 does not mistake Idle_Shoot for walking, or Jump_Idle for jumping only", () => {
    const a = deriveAbilities(["CharacterArmature|Idle_Shoot", "CharacterArmature|Jump_Idle"]);
    expect(a).not.toContain("walk");
    expect(a).not.toContain("run");
  });

  it("C.5 shortClip strips the armature prefix a game does NOT type, but the raw name survives", () => {
    expect(shortClip("AnimalArmature|AnimalArmature|AnimalArmature|Walk")).toBe("Walk");
    expect(shortClip("Gallop")).toBe("Gallop");
  });
});

describe("modelCatalogue — the merged view", () => {
  const cat = modelCatalogue();
  const by = (n: string) => cat.find((c) => c.name === n)!;

  it("C.6 covers every model in the manifest, and nothing else", () => {
    expect(cat.map((c) => c.name).sort()).toEqual([...modelNames].sort());
  });

  it("C.7 the committed abilities file has not drifted from the manifest", () => {
    // It is generated by scripts/model-animation-census.mjs --write. If a model
    // batch lands without re-running that, this is the only thing that notices.
    const missing = cat.filter((c) => c.clips === undefined).map((c) => c.name);
    expect(missing).toEqual([]);
  });

  it("C.8 an animated animal reports what it can actually do", () => {
    const dog = by("dog");
    expect(dog.rigged).toBe(true);
    expect(dog.abilities).toEqual(expect.arrayContaining(["walk", "run", "idle"]));
    expect(dog.clipLabels).toEqual(expect.arrayContaining(["Walk", "Run", "Idle"]));
  });

  it("C.9 a prop reports nothing it cannot do", () => {
    const tree = by("tree");
    expect(tree.rigged).toBe(false);
    expect(tree.abilities).toEqual([]);
  });

  it("C.10 retired models are flagged, with the reason, not silently hidden", () => {
    for (const r of RETIRED) {
      const m = by(r);
      expect(m.retired).toBe(true);
      expect(m.retiredReason!.length).toBeGreaterThan(40);
    }
    expect(cat.filter((c) => !c.retired).length).toBe(cat.length - RETIRED.size);
  });

  it("C.11 CC-BY models carry the credit the licence requires", () => {
    const croc = by("crocodile");
    expect(croc.license).toBe("CC-BY-3.0");
    expect(croc.author).toBeTruthy();
  });
});

describe("the restored facing / real-size data reaches the catalogue (2026-08-23)", () => {
  it("C.17 the horse carries the facing and real size a rider needs", () => {
    const horse = modelCatalogue().find((c) => c.name === "horse")!;
    expect(horse.facing).toBe("+z");
    expect(horse.realSize).toEqual([0.8, 1.7, 2.4]);
    // The horse is skinned, so it has NO published `size` at all — realSize is
    // the only size it has, which is exactly why placeModel has to measure.
    expect(horse.size).toBeUndefined();
  });

  it("C.18 an unaudited model reports neither, rather than a guess", () => {
    const cat = modelCatalogue();
    const unaudited = cat.filter((c) => !c.facing);
    expect(unaudited.length).toBeGreaterThan(0);
    for (const m of unaudited.slice(0, 20)) expect(m.facing, m.name).toBeUndefined();
  });
});

describe("the copy-paste snippets — the 'what can I do with it' half", () => {
  it("C.12 every model gets a marker and a load line using its real name", () => {
    const dog = modelCatalogue().find((c) => c.name === "dog")!;
    expect(dog.usage.marker).toBe("<!--USES_MODELS: dog-->");
    // placeModel since 2026-08-23, for any model whose facing or real size we
    // know: it grounds, sizes and aims in ONE call, where the bare loadModel
    // form left all three to be guessed per game. A model we know nothing
    // about still gets the plain loadModel snippet (C.16).
    expect(dog.usage.load).toContain('placeModel("dog"');
    expect(dog.usage.load).toContain('modelHeading("dog"');
  });

  it("C.13 an animated model gets an AnimationMixer snippet with a REAL clip name", () => {
    const dog = modelCatalogue().find((c) => c.name === "dog")!;
    expect(dog.usage.animate).toBeTruthy();
    expect(dog.usage.animate).toContain("AnimationMixer");
    // The raw clip string, because that is what the game must actually match.
    expect(dog.clips.some((c) => dog.usage.animate!.includes(c))).toBe(true);
  });

  it("C.14 a static model gets NO animate snippet — offering one would be a lie", () => {
    expect(modelCatalogue().find((c) => c.name === "tree")!.usage.animate).toBeUndefined();
  });

  it("C.16 a model with NO facing and NO real size falls back to the plain loadModel snippet", () => {
    // The fallback must stay honest: nothing is grounded, aimed or scaled for
    // a model we have no data on, so the snippet must not pretend otherwise.
    const bare = modelCatalogue().find((c) => !c.facing && !c.realSize);
    expect(bare, "the library should still hold at least one unaudited model").toBeTruthy();
    expect(bare!.usage.load).toContain(`loadModel("${bare!.name}")`);
    expect(bare!.usage.load).not.toContain("placeModel");
  });

  it("C.15 a measured model reports its real-world size so a game can scale it", () => {
    const car = modelCatalogue().find((c) => c.name === "car")!;
    expect(car.size).toHaveLength(3);
    // The snippet now states the REAL-WORLD size in a comment and asks
    // placeModel for it, rather than making the reader do want ÷ actual.
    expect(car.realSize).toHaveLength(3);
    expect(car.usage.load).toContain("m in real life");
    expect(car.usage.load).toContain("metres: true");
  });
});
